apiVersion: v1
kind: Service
metadata:
  name: translation-service
spec:
  selector:
    app: test
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-app
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: yuki0703/translation:latest
          # imagePullPolicy: 
          ports:
            - containerPort: 8000